#!/bin/sh
set -e

lb config noauto \
  --mode debian \
  --architectures amd64 \
  --distribution bookworm \
  --binary-images iso-hybrid \
  --archive-areas "main contrib non-free non-free-firmware" \
  --security true \
  --mirror-chroot-security http://security.debian.org/debian-security \
  --mirror-binary-security http://security.debian.org/debian-security \
  --bootappend-live "boot=live components noeject hostname=cigertool username=root systemd.mask=getty@tty1.service console=tty1" \
  --linux-flavours amd64
